### ISSUE TITLE
Profile syscall_mask and policy index

### ISSUE THREAD

**Issue by blacktop** [spotlightishere/sandtool#1]
I'm curious how your figured out the 2 other fields in the profile_t ? Is there a func in the sandbox kext that validates this?

Thanks!

**Comment by spotlightishere** [comment]
Hi, thank you for the question!

I'm currently utilizing Sandbox.kext as included within the macOS Ventura Kernel Development Kit as a reference. Those names are guesswork from functions such as `get_entry_point_for_indexed_policy` and `profile_populate_syscall_masks` from within `profile_init`/the block of `collection_init`. The initializers validate the length/etc of the individual profile/collection formats, and population functions appear to validate their contents. Not certain any of this is entirely correct - using this project as an opportunity to learn SwiftUI as well 😅

Thank you for all of your work on `ipsw` - it's an invaluable tool!

**Comment by blacktop** [comment]
Maybe instead of syscall_mask it's some kind of flags field?  for the NEW protobox profiles they are ALL set to 1 ? 🤷
